/* eslint-disable */
// Generated from native/process-host/src/protocol.rs. Do not edit.

export const PROCESS_HOST_PROTOCOL_VERSION = 1 as const

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClientMessage = { "type": "start", requestId: string, jobId: string, executable: string, args: Array<string>, cwd: string, env: { [key in string]: string }, logPath: string, timeoutMs: number | null, keepRunningOnTimeout: boolean, retainLog: boolean, spillThresholdChars: number, } | { "type": "cancel", requestId: string, jobId: string, } | { "type": "shutdown", requestId: string, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServerMessage = { "type": "ready", protocolVersion: number, } | { "type": "started", requestId: string, jobId: string, pid: number, } | { "type": "output", jobId: string, sequence: number, chunks: Array<[string, string]>, truncated: boolean, totalBytes: number, } | { "type": "timedOut", jobId: string, } | { "type": "exited", jobId: string, exitCode: number, timedOut: boolean, cancelled: boolean, spilled: boolean, totalBytes: number, error: string | null, } | { "type": "ack", requestId: string, accepted: boolean, } | { "type": "error", requestId: string | null, jobId: string | null, code: string, message: string, };

