export const THINKING_SIDEBAR_PREVIEWS: readonly [string, ...string[]] = [
  'Thinking...',
  'Brewing...',
  'Cerebrating...',
  'Cogitating...',
  'Considering...',
  'Contemplating...',
  'Deciphering...',
  'Deliberating...',
  'Elucidating...',
  'Envisioning...',
  'Ideating...',
  'Imagining...',
  'Incubating...',
  'Inferring...',
  'Mulling...',
  'Musing...',
  'Noodling...',
  'Perusing...',
  'Philosophising...',
  'Pondering...',
  'Puzzling...',
  'Ruminating...'
]

export const WORKING_SIDEBAR_PREVIEWS: readonly [string, ...string[]] = [
  'Accomplishing...',
  'Actualizing...',
  'Baking...',
  'Beaming...',
  'Billowing...',
  'Boogieing...',
  'Booping...',
  'Caramelizing...',
  'Cascading...',
  'Channeling...',
  'Choreographing...',
  'Churning...',
  'Coalescing...',
  'Combobulating...',
  'Composing...',
  'Concocting...',
  'Cooking...',
  'Crafting...',
  'Creating...',
  'Crystallizing...',
  'Cultivating...',
  'Doodling...',
  'Drizzling...',
  'Ebbing...',
  'Embellishing...',
  'Enchanting...',
  'Fermenting...',
  'Flowing...',
  'Fluttering...',
  'Forming...',
  'Frosting...',
  'Garnishing...',
  'Germinating...',
  'Grooving...',
  'Gusting...',
  'Harmonizing...',
  'Hatching...',
  'Improvising...',
  'Infusing...',
  'Kneading...',
  'Leavening...',
  'Levitating...',
  'Manifesting...',
  'Marinating...',
  'Metamorphosing...',
  'Misting...',
  'Orbiting...',
  'Orchestrating...',
  'Percolating...',
  'Polishing...',
  'Prestidigitating...',
  'Proofing...',
  'Propagating...',
  'Recombobulating...',
  'Seasoning...',
  'Shaping...',
  'Shimmying...',
  'Simmering...',
  'Sketching...',
  'Smooshing...',
  'Spinning...',
  'Sprouting...',
  'Stewing...',
  'Swirling...',
  'Tempering...',
  'Tinkering...',
  'Transfiguring...',
  'Transmuting...',
  'Twisting...',
  'Undulating...',
  'Unfurling...',
  'Unravelling...',
  'Vibing...',
  'Wandering...',
  'Warping...',
  'Whirlpooling...',
  'Whirring...',
  'Whisking...',
  'Working...',
  'Wrangling...',
  'Zesting...',
  'Zigzagging...'
]

export function pickSidebarPlaceholder(
  seed: string,
  labels: readonly [string, ...string[]]
): string {
  let hash = 0
  for (let index = 0; index < seed.length; index += 1) {
    hash = (hash * 31 + seed.charCodeAt(index)) >>> 0
  }
  return labels[hash % labels.length]
}

export function makeRunningPlaceholderSeed(
  activeRunId: string | null,
  fallbackId: string,
  state: 'thinking' | 'working'
): string {
  return activeRunId ? `run:${activeRunId}:${state}` : `thread:${fallbackId}:${state}`
}
