import { app } from 'electron'
import { is } from '@electron-toolkit/utils'
import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { dirname, join } from 'node:path'
import { resolveYachiyoDataDir } from './yachiyo-server/config/paths.ts'

const PATH_MARKER = '# Added by Yachiyo CLI'

export function resolveCLIBinDir(): string {
  return join(resolveYachiyoDataDir(), 'bin')
}

function resolveCLIWrapperPath(): string {
  return join(resolveCLIBinDir(), 'yachiyo')
}

function shellQuote(str: string): string {
  return `'${str.replace(/'/gu, "'\\''")}'`
}

function buildWrapperContent(): string {
  const exePath = process.execPath
  const appPath = app.getAppPath()

  const header = [
    '#!/usr/bin/env bash',
    '# Auto-generated by Yachiyo. Do not edit manually.',
    '# Re-launch Yachiyo to update this file.'
  ]

  if (is.dev) {
    const cliScript = join(appPath, 'src/main/yachiyo-server/app/yachiyo-cli.ts')
    return [
      ...header,
      `ELECTRON_RUN_AS_NODE=1 exec ${shellQuote(exePath)} --experimental-strip-types ${shellQuote(cliScript)} "$@"`,
      ''
    ].join('\n')
  }

  const cliBundle = join(appPath, 'out/main/yachiyo-cli.js')
  return [
    ...header,
    `ELECTRON_RUN_AS_NODE=1 exec ${shellQuote(exePath)} ${shellQuote(cliBundle)} "$@"`,
    ''
  ].join('\n')
}

function installWrapper(): void {
  const binDir = resolveCLIBinDir()
  const wrapperPath = resolveCLIWrapperPath()
  mkdirSync(binDir, { recursive: true })
  writeFileSync(wrapperPath, buildWrapperContent(), 'utf8')
  chmodSync(wrapperPath, 0o755)
}

function isWrapperCurrent(): boolean {
  const wrapperPath = resolveCLIWrapperPath()
  if (!existsSync(wrapperPath)) return false
  try {
    return readFileSync(wrapperPath, 'utf8') === buildWrapperContent()
  } catch {
    return false
  }
}

function buildPosixPathLine(binDir: string): string {
  const home = homedir()
  const displayDir = binDir.startsWith(home + '/') ? '$HOME' + binDir.slice(home.length) : binDir
  return `export PATH="${displayDir}:$PATH"`
}

function buildFishPathLine(binDir: string): string {
  return `fish_add_path ${shellQuote(binDir)}`
}

function profileNeedsUpdate(
  profilePath: string,
  pathLine: string,
  createIfMissing: boolean
): boolean {
  if (!existsSync(profilePath)) return createIfMissing
  const content = readFileSync(profilePath, 'utf8')
  return !content.includes(PATH_MARKER) && !content.includes(pathLine)
}

function appendToProfile(profilePath: string, pathLine: string, createIfMissing = true): void {
  if (!profileNeedsUpdate(profilePath, pathLine, createIfMissing)) return
  mkdirSync(dirname(profilePath), { recursive: true })
  const existing = existsSync(profilePath) ? readFileSync(profilePath, 'utf8') : ''
  const separator = existing && !existing.endsWith('\n') ? '\n' : ''
  writeFileSync(profilePath, `${existing}${separator}${PATH_MARKER}\n${pathLine}\n`, 'utf8')
}

function ensurePathInShellProfiles(): void {
  const binDir = resolveCLIBinDir()
  const posixLine = buildPosixPathLine(binDir)
  const fishLine = buildFishPathLine(binDir)
  const home = homedir()

  const posixProfiles = [join(home, '.zshrc'), join(home, '.bashrc'), join(home, '.bash_profile')]

  for (const profilePath of posixProfiles) {
    try {
      appendToProfile(profilePath, posixLine)
    } catch (error) {
      console.warn(`[cli-setup] Could not update ${profilePath}:`, error)
    }
  }

  const fishConfig = join(home, '.config', 'fish', 'config.fish')
  const fishBinaryExists =
    existsSync('/opt/homebrew/bin/fish') ||
    existsSync('/usr/local/bin/fish') ||
    existsSync('/usr/bin/fish')
  try {
    appendToProfile(fishConfig, fishLine, fishBinaryExists)
  } catch (error) {
    console.warn(`[cli-setup] Could not update ${fishConfig}:`, error)
  }
}

export function setupCLI(): void {
  try {
    if (!isWrapperCurrent()) {
      installWrapper()
      console.log(`[cli-setup] Installed yachiyo CLI at ${resolveCLIWrapperPath()}`)
    }
    ensurePathInShellProfiles()
  } catch (error) {
    console.error('[cli-setup] Setup failed:', error)
  }
}
