export function shellQuote(value: string): string {
  return `'${value.replace(/'/gu, "'\\''")}'`
}

function powershellQuote(value: string): string {
  return `'${value.replace(/'/gu, "''")}'`
}

export function buildWindowsCLIUninstallScript(binDir: string): string {
  return [
    `$target = ${powershellQuote(binDir)}`,
    "$targetKey = $target.Trim().TrimEnd([char[]]'\\/').ToLowerInvariant()",
    "$current = [string][Environment]::GetEnvironmentVariable('Path', 'User')",
    "$entries = @($current -split ';' | Where-Object { $_.Trim().TrimEnd([char[]]'\\/').ToLowerInvariant() -ne $targetKey })",
    "$updated = $entries -join ';'",
    "if ($updated -ne $current) { [Environment]::SetEnvironmentVariable('Path', $updated, 'User') }",
    '$signature = \'[DllImport("user32.dll", SetLastError=true, CharSet=CharSet.Auto)] public static extern IntPtr SendMessageTimeout(IntPtr hWnd,uint Msg,UIntPtr wParam,string lParam,uint flags,uint timeout,out UIntPtr result);\'',
    'Add-Type -MemberDefinition $signature -Name NativeMethods -Namespace Yachiyo',
    '$result = [UIntPtr]::Zero',
    "[Yachiyo.NativeMethods]::SendMessageTimeout([IntPtr]0xffff,0x1a,[UIntPtr]::Zero,'Environment',2,5000,[ref]$result) | Out-Null",
    "Remove-Item -LiteralPath (Join-Path $target 'yachiyo.cmd') -Force -ErrorAction SilentlyContinue",
    "Remove-Item -LiteralPath (Join-Path $target 'yachiyo') -Force -ErrorAction SilentlyContinue",
    'Remove-Item -LiteralPath $PSCommandPath -Force -ErrorAction SilentlyContinue',
    ''
  ].join('\r\n')
}

export function buildWindowsBashCLIWrapperContent(input: {
  developmentMode: boolean
  executablePath: string
  appPath: string
}): string {
  const executable = `"$(cygpath -u -- ${shellQuote(input.executablePath)})"`
  const command = input.developmentMode
    ? `exec ${executable} ${shellQuote(input.appPath)} --yachiyo-cli "$@"`
    : `exec ${executable} --yachiyo-cli "$@"`

  return [
    '#!/usr/bin/env bash',
    '# Auto-generated by Yachiyo. Do not edit manually.',
    command,
    ''
  ].join('\n')
}

export function buildCLIWrapperContent(input: {
  platform: NodeJS.Platform
  developmentMode: boolean
  executablePath: string
  appPath: string
}): string {
  if (input.platform === 'win32') {
    const launch = input.developmentMode
      ? `"${input.executablePath}" "${input.appPath}" --yachiyo-cli %*`
      : `"${input.executablePath}" --yachiyo-cli %*`
    return [
      '@echo off',
      'rem Auto-generated by Yachiyo. Do not edit manually.',
      launch,
      'exit /b %errorlevel%',
      ''
    ].join('\r\n')
  }

  const header = [
    '#!/usr/bin/env bash',
    '# Auto-generated by Yachiyo. Do not edit manually.',
    '# Re-launch Yachiyo to update this file.'
  ]
  const command = input.developmentMode
    ? `exec ${shellQuote(input.executablePath)} ${shellQuote(input.appPath)} --yachiyo-cli "$@"`
    : `exec ${shellQuote(input.executablePath)} --yachiyo-cli "$@"`

  return [...header, command, ''].join('\n')
}
