export function shellQuote(value: string): string {
  return `'${value.replace(/'/gu, "'\\''")}'`
}

export function buildCLIWrapperContent(input: {
  developmentMode: boolean
  executablePath: string
  appPath: string
}): string {
  const header = [
    '#!/usr/bin/env bash',
    '# Auto-generated by Yachiyo. Do not edit manually.',
    '# Re-launch Yachiyo to update this file.'
  ]
  const command = input.developmentMode
    ? `exec ${shellQuote(input.executablePath)} ${shellQuote(input.appPath)} --yachiyo-cli "$@"`
    : `exec ${shellQuote(input.executablePath)} --yachiyo-cli "$@"`

  return [...header, command, ''].join('\n')
}
