/* eslint-disable @typescript-eslint/explicit-function-return-type */
// Generates the iOS design tokens from the desktop palettes so both apps share one source.
//   pnpm run ios:theme            write apps/ios/.../Generated/YachiyoTheme.swift
//   pnpm run ios:theme -- --check  fail when the committed file is stale
import { readFile, mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { THEME_OPTIONS, themeRgbTokenVars } from '../packages/shared/src/theme/themePalettes.ts'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const outputPath = resolve(
  root,
  'apps/ios/YachiyoChatUI/Sources/YachiyoMaterial/Generated/YachiyoTheme.swift'
)
const tokens = Object.keys(themeRgbTokenVars)

function rgb(value, context) {
  const parts = value.trim().split(/\s+/).map(Number)
  if (
    parts.length !== 3 ||
    parts.some((part) => !Number.isInteger(part) || part < 0 || part > 255)
  ) {
    throw new Error(`Unexpected RGB value "${value}" for ${context}`)
  }
  return `.init(${parts.join(', ')})`
}

function palette(option, variant) {
  const values = option.palettes[variant]
  const args = tokens
    .map(
      (token) => `            ${token}: ${rgb(values[token], `${option.id}.${variant}.${token}`)}`
    )
    .join(',\n')
  return `        case (.${option.id}, .${variant}):\n            return YachiyoPalette(\n${args}\n            )`
}

const swift = `// Generated by \`pnpm run ios:theme\` from packages/shared/src/theme/themePalettes.ts.
// Do not edit; change the desktop palette and regenerate.

public enum YachiyoThemeID: String, CaseIterable, Sendable {
${THEME_OPTIONS.map((option) => `    case ${option.id}`).join('\n')}

    public var displayName: String {
        switch self {
${THEME_OPTIONS.map((option) => `        case .${option.id}: return ${JSON.stringify(option.label)}`).join('\n')}
        }
    }
}

public enum YachiyoThemeVariant: Sendable {
    case light
    case dark
}

/// One palette's semantic colors as 8-bit sRGB triples, named like the desktop CSS tokens.
public struct YachiyoPalette: Equatable, Sendable {
${tokens.map((token) => `    public let ${token}: YachiyoRGB`).join('\n')}
}

public enum YachiyoThemePalettes {
    public static func palette(_ id: YachiyoThemeID, _ variant: YachiyoThemeVariant) -> YachiyoPalette {
        switch (id, variant) {
${THEME_OPTIONS.flatMap((option) => [palette(option, 'light'), palette(option, 'dark')]).join('\n')}
        }
    }
}
`

const current = await readFile(outputPath, 'utf8').catch(() => null)
if (process.argv.includes('--check')) {
  if (current !== swift) {
    console.error('YachiyoTheme.swift is stale. Run: pnpm run ios:theme')
    process.exit(1)
  }
  console.log('YachiyoTheme.swift is up to date')
} else if (current !== swift) {
  await mkdir(dirname(outputPath), { recursive: true })
  await writeFile(outputPath, swift)
  console.log('wrote YachiyoTheme.swift')
}
