// Generates Swift Codable types for the remote protocol from the committed JSON Schema
// (itself generated from the zod definitions by `pnpm run remote:codegen`).
//   pnpm run ios:codegen            write apps/ios/YachiyoRemoteKit/.../Generated/RemoteProtocol.swift
//   pnpm run ios:codegen -- --check  fail when the committed file is stale
import { execFileSync } from 'node:child_process'
import { mkdtempSync, readFileSync, rmSync, writeFileSync, mkdirSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const schemaPath = resolve(root, 'packages/shared/src/remote/generated/remote-protocol.schema.json')
const outputPath = resolve(
  root,
  'apps/ios/YachiyoRemoteKit/Sources/YachiyoRemoteKit/Generated/RemoteProtocol.swift'
)
const check = process.argv.includes('--check')

// quicktype only emits types reachable from the top level, so wrap every $def in one object.
const schema = JSON.parse(readFileSync(schemaPath, 'utf8'))
const definitions = JSON.parse(
  JSON.stringify(schema.$defs).replaceAll('#/$defs/', '#/definitions/')
)
const wrapper = {
  $schema: 'http://json-schema.org/draft-07/schema#',
  title: 'RemoteProtocolTypes',
  type: 'object',
  properties: Object.fromEntries(
    Object.keys(definitions)
      .sort()
      .map((name) => [name, { $ref: `#/definitions/${name}` }])
  ),
  definitions
}

const workDir = mkdtempSync(join(tmpdir(), 'yachiyo-ios-codegen-'))
try {
  const input = join(workDir, 'schema.json')
  const output = join(workDir, 'RemoteProtocol.swift')
  writeFileSync(input, JSON.stringify(wrapper))
  execFileSync(
    resolve(root, 'node_modules/.bin/quicktype'),
    [
      '--src-lang',
      'schema',
      '--lang',
      'swift',
      '--top-level',
      'RemoteProtocolTypes',
      '--struct-or-class',
      'struct',
      '--access-level',
      'public',
      '--protocol',
      'equatable',
      '--sendable',
      '--no-initializers',
      '--no-date-times',
      '--acronym-style',
      'camel',
      '--density',
      'dense',
      '-o',
      output,
      input
    ],
    { stdio: ['ignore', 'ignore', 'inherit'] }
  )
  const header =
    '// Generated by `pnpm run ios:codegen` from packages/shared/src/remote/generated/\n' +
    '// remote-protocol.schema.json with quicktype. Do not edit.\n\n'
  const next = header + readFileSync(output, 'utf8')
  let current = null
  try {
    current = readFileSync(outputPath, 'utf8')
  } catch {
    current = null
  }
  if (check) {
    if (current !== next) {
      console.error('RemoteProtocol.swift is stale. Run: pnpm run ios:codegen')
      process.exit(1)
    }
    console.log('RemoteProtocol.swift is up to date')
  } else if (current !== next) {
    mkdirSync(dirname(outputPath), { recursive: true })
    writeFileSync(outputPath, next)
    console.log('wrote RemoteProtocol.swift')
  }
} finally {
  rmSync(workDir, { recursive: true, force: true })
}
