/**
 * Self-contained worker script for jsReplTool. Spawned via:
 *
 *   new Worker(JS_REPL_WORKER_SCRIPT, { eval: true })
 *
 * The script string is plain JavaScript (not TypeScript) so it can be evaluated
 * directly without a build step.
 */

const JS_REPL_WORKER_SCRIPT_LINES: string[] = [
  "const { parentPort } = require('node:worker_threads')",
  "const vm = require('node:vm')",
  "const { createRequire } = require('node:module')",
  "const { statSync } = require('node:fs')",
  "const { isAbsolute, resolve: resolvePath } = require('node:path')",
  '',
  'function relaxRequireBindings(code) {',
  "  return code.replace(/\\b(const|let)\\s+([\\w{},\\s]+?)\\s*=\\s*require\\s*\\(/g, 'var $2 = require(')",
  '}',
  '',
  'function isThenable(value) {',
  '  return (',
  "    value != null && typeof value === 'object' && typeof value.then === 'function'",
  '  )',
  '}',
  '',
  'function formatResult(value) {',
  "  if (typeof value === 'string') return value",
  '  try {',
  '    return JSON.stringify(value, null, 2)',
  '  } catch {',
  '    return String(value)',
  '  }',
  '}',
  '',
  'const AsyncFunction = (async () => {}).constructor',
  '',
  'function wrapLastExpression(code) {',
  '  const trimmed = code.trimEnd()',
  '  if (!trimmed) return code',
  '',
  '  if (/\\breturn\\b/.test(trimmed)) return code',
  '',
  '  const tryParse = (candidate) => {',
  '    try {',
  '      new AsyncFunction(candidate)',
  '      return true',
  '    } catch {',
  '      return false',
  '    }',
  '  }',
  '',
  '  const asReturn = `return (\\n${trimmed}\\n)`',
  '  if (tryParse(asReturn)) return asReturn',
  '',
  "  const lines = trimmed.split('\\n')",
  '  let lastIdx = lines.length - 1',
  "  while (lastIdx >= 0 && lines[lastIdx].trim() === '') {",
  '    lastIdx--',
  '  }',
  '  if (lastIdx < 0) return code',
  '',
  '  const lastLine = lines[lastIdx]',
  '',
  "  const lastSemicolon = lastLine.lastIndexOf(';')",
  '  if (lastSemicolon >= 0) {',
  '    const before = lastLine.slice(0, lastSemicolon + 1)',
  '    const after = lastLine.slice(lastSemicolon + 1).trim()',
  '    if (after) {',
  "      const candidate = [...lines.slice(0, lastIdx), before, `return (${after})`].join('\\n')",
  '      if (tryParse(candidate)) return candidate',
  '    }',
  '  }',
  '',
  "  const candidate = [...lines.slice(0, lastIdx), `return (${lastLine})`].join('\\n')",
  '  if (tryParse(candidate)) return candidate',
  '',
  '  return code',
  '}',
  '',
  'class TimerTracker {',
  '  constructor() {',
  '    this.timeouts = new Set()',
  '    this.intervals = new Set()',
  '    this.onCallbackError = undefined',
  '  }',
  '',
  '  handleCallbackError(error) {',
  '    const message = error instanceof Error ? error.message : String(error)',
  '    if (this.onCallbackError) {',
  '      this.onCallbackError(message)',
  '    } else {',
  "      console.error('[jsRepl] Timer callback threw (suppressed):', message)",
  '    }',
  '  }',
  '',
  '  trackedSetTimeout(callback, ms) {',
  '    const self = this',
  '    const handle = setTimeout(function (...args) {',
  '      self.timeouts.delete(handle)',
  '      try {',
  '        callback(...args)',
  '      } catch (error) {',
  '        self.handleCallbackError(error)',
  '      }',
  '    }, ms)',
  '    this.timeouts.add(handle)',
  '    return handle',
  '  }',
  '',
  '  trackedSetInterval(callback, ms) {',
  '    const self = this',
  '    const handle = setInterval(function (...args) {',
  '      try {',
  '        callback(...args)',
  '      } catch (error) {',
  '        self.handleCallbackError(error)',
  '      }',
  '    }, ms)',
  '    this.intervals.add(handle)',
  '    return handle',
  '  }',
  '',
  '  trackedClearTimeout(handle) {',
  '    clearTimeout(handle)',
  '    this.timeouts.delete(handle)',
  '  }',
  '',
  '  trackedClearInterval(handle) {',
  '    clearInterval(handle)',
  '    this.intervals.delete(handle)',
  '  }',
  '',
  '  clearAll() {',
  '    for (const handle of this.timeouts) {',
  '      clearTimeout(handle)',
  '    }',
  '    this.timeouts.clear()',
  '    for (const handle of this.intervals) {',
  '      clearInterval(handle)',
  '    }',
  '    this.intervals.clear()',
  '  }',
  '}',
  '',
  'function makeCapturingConsole(lines) {',
  '  const format = (...args) => args.map((a) => {',
  "    if (typeof a === 'string') return a",
  '    try {',
  '      return JSON.stringify(a, null, 2) ?? String(a)',
  '    } catch {',
  '      return String(a)',
  '    }',
  "  }).join(' ')",
  '',
  '  return {',
  '    log:  (...args) => lines.push(format(...args)),',
  '    warn: (...args) => lines.push(`[warn] ${format(...args)}`),',
  '    error:(...args) => lines.push(`[error] ${format(...args)}`),',
  '    info: (...args) => lines.push(format(...args)),',
  '    debug:(...args) => lines.push(`[debug] ${format(...args)}`)',
  '  }',
  '}',
  '',
  'function resolveCallCwd(workspacePath, requested) {',
  '  if (!requested) return { resolved: workspacePath }',
  '  const resolved = resolvePath(workspacePath, requested)',
  "  if (resolved !== workspacePath && !resolved.startsWith(workspacePath + '/')) {",
  "    return { error: `Invalid cwd '${requested}'` }",
  '  }',
  '  try {',
  '    const info = statSync(resolved)',
  '    if (!info.isDirectory()) {',
  "      return { error: `Invalid cwd '${requested}' — not a directory.` }",
  '    }',
  '  } catch {',
  "    return { error: `Invalid cwd '${requested}' — directory does not exist.` }",
  '  }',
  '  return { resolved }',
  '}',
  '',
  'function wrapFsForCwd(fsModule, cwdRef) {',
  "  const path = require('node:path')",
  '  return new Proxy(fsModule, {',
  '    get(target, prop) {',
  '      const val = target[prop]',
  "      if (typeof val !== 'function') return val",
  '      return function(...args) {',
  "        if (args.length > 0 && typeof args[0] === 'string' && !path.isAbsolute(args[0])) {",
  '          args[0] = path.resolve(cwdRef.value, args[0])',
  '        }',
  '        return val.apply(target, args)',
  '      }',
  '    }',
  '  })',
  '}',
  '',
  'function createMockProcess(cwdRef) {',
  '  const target = { env: { ...process.env } }',
  '  return new Proxy(target, {',
  '    get(t, prop) {',
  "      if (prop === 'cwd') {",
  '        return () => cwdRef.value',
  '      }',
  "      if (prop === 'env') {",
  '        return t.env',
  '      }',
  "      if (prop === 'chdir') {",
  '        return () => {}',
  '      }',
  '      const val = process[prop]',
  "      return typeof val === 'function' ? val.bind(process) : val",
  '    }',
  '  })',
  '}',
  '',
  'function wrapChildProcessForCwd(cpModule, cwdRef) {',
  "  const methodsWithOptions = ['exec', 'execSync', 'execFile', 'execFileSync', 'spawn', 'spawnSync', 'fork']",
  "  const encodingAsString = ['execSync']",
  '',
  '  function injectCwd(args, method) {',
  '    const last = args[args.length - 1]',
  "    if (typeof last === 'function') {",
  '      const secondLast = args[args.length - 2]',
  '      if (',
  '        args.length >= 2 &&',
  "        typeof secondLast === 'object' &&",
  '        secondLast !== null &&',
  '        !Array.isArray(secondLast)',
  '      ) {',
  '        const newOptions = { cwd: cwdRef.value, ...secondLast }',
  '        return [...args.slice(0, -2), newOptions, last]',
  '      }',
  '      return [...args.slice(0, -1), { cwd: cwdRef.value }, last]',
  '    }',
  "    if (args.length === 2 && typeof args[1] === 'string' && encodingAsString.includes(method)) {",
  '      return [args[0], { encoding: args[1], cwd: cwdRef.value }]',
  '    }',
  '    const lastNoCb = args[args.length - 1]',
  '    if (',
  '      args.length >= 1 &&',
  "      typeof lastNoCb === 'object' &&",
  '      lastNoCb !== null &&',
  '      !Array.isArray(lastNoCb)',
  '    ) {',
  '      const newOptions = { cwd: cwdRef.value, ...lastNoCb }',
  '      return [...args.slice(0, -1), newOptions]',
  '    }',
  '    return [...args, { cwd: cwdRef.value }]',
  '  }',
  '',
  '  return new Proxy(cpModule, {',
  '    get(target, prop) {',
  '      const val = target[prop]',
  "      if (typeof val !== 'function') return val",
  '      if (!methodsWithOptions.includes(prop)) {',
  '        return function(...args) {',
  '          return val.apply(target, args)',
  '        }',
  '      }',
  '      return function(...args) {',
  '        return val.apply(target, injectCwd(args, prop))',
  '      }',
  '    }',
  '  })',
  '}',
  '',
  'function createSandboxRequire(workspacePath, cwdRef, mockProcess, wrappedCp) {',
  "  const baseRequire = createRequire(resolvePath(workspacePath, 'package.json'))",
  "  const wrappedFs = wrapFsForCwd(require('node:fs'), cwdRef)",
  '  return function(id) {',
  "    if (id === 'fs' || id === 'node:fs') {",
  '      return wrappedFs',
  '    }',
  "    if (id === 'process' || id === 'node:process') {",
  '      return mockProcess',
  '    }',
  "    if (id === 'child_process' || id === 'node:child_process') {",
  '      return wrappedCp',
  '    }',
  '    return baseRequire(id)',
  '  }',
  '}',
  '',
  'function createFreshContext(workspacePath, cwdRef, timerTracker, toolBindings) {',
  '  const mockProcess = createMockProcess(cwdRef)',
  "  const wrappedCp = wrapChildProcessForCwd(require('node:child_process'), cwdRef)",
  '  const sandbox = {',
  '    require: createSandboxRequire(workspacePath, cwdRef, mockProcess, wrappedCp),',
  '    __dirname: workspacePath,',
  "    __filename: workspacePath + '/jsRepl.js',",
  '    process: mockProcess,',
  '    setTimeout:  (cb, ms) => timerTracker.trackedSetTimeout(cb, ms),',
  '    setInterval: (cb, ms) => timerTracker.trackedSetInterval(cb, ms),',
  '    clearTimeout:  (handle) => timerTracker.trackedClearTimeout(handle),',
  '    clearInterval: (handle) => timerTracker.trackedClearInterval(handle),',
  '    tools: toolBindings,',
  '    Buffer,',
  '    URL,',
  '    URLSearchParams,',
  '    TextEncoder,',
  '    TextDecoder,',
  '    console',
  '  }',
  '  return vm.createContext(sandbox)',
  '}',
  '',
  'const state = {',
  "  workspacePath: '',",
  '  vmContext: null,',
  '  timerTracker: null,',
  "  cwdRef: { value: '' },",
  '  toolResolvers: new Map(),',
  '  toolCallId: 1,',
  '  enabledTools: []',
  '}',
  '',
  'function buildToolBindings() {',
  '  const bindings = {}',
  '  for (const name of state.enabledTools) {',
  '    bindings[name] = async (input) => {',
  '      const id = state.toolCallId++',
  '      return new Promise((resolve) => {',
  '        state.toolResolvers.set(id, resolve)',
  "        parentPort.postMessage({ type: 'toolCall', id, toolName: name, input })",
  '      })',
  '    }',
  '  }',
  '  return bindings',
  '}',
  '',
  'function resetContext() {',
  '  if (state.timerTracker) {',
  '    state.timerTracker.clearAll()',
  '  }',
  '  state.timerTracker = new TimerTracker()',
  '  state.cwdRef.value = state.workspacePath',
  '  const toolBindings = buildToolBindings()',
  '  state.vmContext = createFreshContext(state.workspacePath, state.cwdRef, state.timerTracker, toolBindings)',
  '}',
  '',
  "parentPort.on('message', async (message) => {",
  "  if (message.type === 'init') {",
  '    state.workspacePath = message.workspacePath',
  '    state.enabledTools = message.enabledTools || []',
  '    resetContext()',
  "    parentPort.postMessage({ type: 'initDone' })",
  '    return',
  '  }',
  '',
  "  if (message.type === 'toolResult') {",
  '    const resolver = state.toolResolvers.get(message.id)',
  '    if (resolver) {',
  '      state.toolResolvers.delete(message.id)',
  '      resolver(message.result)',
  '    }',
  '    return',
  '  }',
  '',
  "  if (message.type === 'execute') {",
  '    const { code, timeoutMs, cwd, reset } = message',
  '',
  '    if (reset) {',
  '      resetContext()',
  '    }',
  '',
  '    const consoleLines = []',
  '    state.timerTracker.onCallbackError = (msg) => {',
  '      consoleLines.push(`[error] Timer callback error: ${msg}`)',
  '    }',
  '    state.vmContext.console = makeCapturingConsole(consoleLines)',
  '',
  '    let result',
  '    let error',
  '    let timedOut = false',
  '',
  '    const callCwd = cwd || state.workspacePath',
  '    const previousCwd = process.cwd()',
  '    state.cwdRef.value = callCwd',
  '    state.vmContext.__dirname = callCwd',
  "    state.vmContext.__filename = callCwd + '/jsRepl.js'",
  '    // Refresh the env copy so REPL-local mutations do not leak across calls.',
  '    state.vmContext.process.env = { ...process.env }',
  '    // process.chdir() is unsupported in worker threads (ERR_WORKER_UNSUPPORTED_OPERATION).',
  '    // Cwd for fs operations is handled by wrapFsForCwd; cwd for process/child_process',
  '    // is handled by createMockProcess and wrapChildProcessForCwd.',
  '    try { process.chdir(callCwd) } catch {}',
  '',
  '    try {',
  '      let rawResult',
  '      const relaxedCode = relaxRequireBindings(code)',
  '',
  '      try {',
  '        rawResult = vm.runInContext(relaxedCode, state.vmContext, {',
  '          timeout: timeoutMs,',
  "          filename: 'jsRepl'",
  '        })',
  '      } catch (syncErr) {',
  "        const errMsg = syncErr instanceof Error ? syncErr.message : String(syncErr?.message || '')",
  "        if (errMsg.includes('await is only valid in async function')) {",
  '          rawResult = vm.runInContext(',
  '            `(async () => {\\n${wrapLastExpression(relaxedCode)}\\n})()`,',
  '            state.vmContext,',
  "            { timeout: timeoutMs, filename: 'jsRepl' }",
  '          )',
  '        } else {',
  '          throw syncErr',
  '        }',
  '      }',
  '',
  '      if (isThenable(rawResult)) {',
  '        let raceTimer',
  '        try {',
  '          rawResult = await Promise.race([',
  '            rawResult,',
  '            new Promise((_, reject) => {',
  "              raceTimer = setTimeout(() => reject(new Error('Script execution timed out.')), timeoutMs)",
  '            })',
  '          ])',
  '        } finally {',
  '          if (raceTimer !== undefined) clearTimeout(raceTimer)',
  '        }',
  '      }',
  '',
  '      if (rawResult !== undefined) {',
  '        result = formatResult(rawResult)',
  '      }',
  '    } catch (err) {',
  '      const errObj = err || {}',
  "      if (errObj.code === 'ERR_SCRIPT_EXECUTION_TIMEOUT' ||",
  "          (typeof errObj.message === 'string' && errObj.message.includes('Script execution timed out'))) {",
  '        timedOut = true',
  '        error = `Script execution timed out (${Math.round(timeoutMs / 1000)}s limit).`',
  '      } else if (err instanceof Error) {',
  '        error = `${err.name}: ${err.message}`',
  "      } else if (typeof errObj.message === 'string') {",
  "        error = `${errObj.name || 'Error'}: ${errObj.message}`",
  '      } else {',
  '        error = String(err)',
  '      }',
  '    } finally {',
  '      try { process.chdir(previousCwd) } catch {}',
  '      state.timerTracker.clearAll()',
  '    }',
  '',
  '    parentPort.postMessage({',
  "      type: 'result',",
  '      result,',
  '      consoleLines,',
  '      error,',
  '      timedOut',
  '    })',
  '  }',
  '})'
]

export const JS_REPL_WORKER_SCRIPT = JS_REPL_WORKER_SCRIPT_LINES.join('\n')
